GET http://localhost:5000/planes HTTP/1.1

###

POST https://localhost:5000/plane/1 HTTP/1.1
content-type: application/json

{
   "id": 1,
   "name": "D-5318",
   "model": "K6CR",
   "manufacturer": "Alexander Schleicher"
}